// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD18qftenWYtgmOeXzI2-OOEW18xODDMuk',
    appId: '1:927282346859:web:c25f41e2977d77db64ea2e',
    messagingSenderId: '927282346859',
    projectId: 'flutterapp-ed226',
    authDomain: 'flutterapp-ed226.firebaseapp.com',
    databaseURL: 'https://flutterapp-ed226-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-ed226.appspot.com',
    measurementId: 'G-BKF353S053',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-eUfBJYD3F3arxVT0FDJSTUN0pfXq6c',
    appId: '1:927282346859:android:da364d7a061ed60964ea2e',
    messagingSenderId: '927282346859',
    projectId: 'flutterapp-ed226',
    databaseURL: 'https://flutterapp-ed226-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-ed226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxLKI6WqQNKptaxeZxYB2F4kJEuR4scZU',
    appId: '1:927282346859:ios:04746d73445a960064ea2e',
    messagingSenderId: '927282346859',
    projectId: 'flutterapp-ed226',
    databaseURL: 'https://flutterapp-ed226-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-ed226.appspot.com',
    iosBundleId: 'com.example.myStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxLKI6WqQNKptaxeZxYB2F4kJEuR4scZU',
    appId: '1:927282346859:ios:4143481347a9d6b664ea2e',
    messagingSenderId: '927282346859',
    projectId: 'flutterapp-ed226',
    databaseURL: 'https://flutterapp-ed226-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutterapp-ed226.appspot.com',
    iosBundleId: 'com.example.myStorage.RunnerTests',
  );
}
